name: shelf_modular
description: Smart project structure with dependency injection and route management
version: 0.0.1
homepage: https://github.com/Flutterando/modular

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  modular_core: ">=0.0.15 <=1.0.0"
  mime: ^1.0.0
  http_parser: ^4.0.0

dev_dependencies:
  mocktail: ^0.1.4
  pedantic: ^1.10.0
  test: ^1.17.10
