name: modular_core
description: Smart project structure with dependency injection and route management
version: 0.0.15
homepage: https://github.com/Flutterando/modular

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  characters: ^1.1.0
  meta: ^1.3.0
  modular_interfaces: ">=0.0.9 <1.0.0"

dev_dependencies:
  test: ^1.17.10

scripts:
  coverage: wsl genhtml -o coverage/html coverage/lcov.info