name: modular_core
description: Smart project structure with dependency injection and route management
version: 0.0.4
homepage: https://github.com/Flutterando/modular

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  characters: ^1.1.0
  meta: ^1.3.0
  modular_interfaces: ^0.0.1+2

dev_dependencies:
  test: ^1.17.10

