name: CI

on: 
  pull_request:
    branches: 
      - master
    
jobs:
  test:
    name: Flutter Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.3.0
    - uses: subosito/flutter-action@v1.3.2
      with:
        flutter-version: '1.12.13+hotfix.8'
    - run: flutter pub get
    - run: flutter test --coverage
    - name: Code coverage
      id: dart-coverage
      uses: johnpryan/dart-coverage-action@master
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.github_token }}
