name: CI

on: 
  pull_request:
    branches: 
      - master
jobs:
  flutter_modular:
    name: flutter modular tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.0'
    
    - name: get packages
      run: flutter pub get
      working-directory: flutter_modular
    
    - name: Flutter Test
      run: flutter test --coverage --coverage-path ../coverage/lcov.info .
      working-directory: flutter_modular
      
    - name: Codecov GitHub Action
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  modular_core:
    name: modular core tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.0'
    
    - name: get packages
      run: flutter pub get
      working-directory: modular_core
    
    - name: Flutter Test
      run: flutter test --coverage --coverage-path ../coverage/lcov.info .
      working-directory: modular_core
      
    - name: Codecov GitHub Action
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        
  shelf_modular:
    name: shelf modular tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.0'
    
    - name: get packages
      run: flutter pub get
      working-directory: shelf_modular
    
    - name: Flutter Test
      run: flutter test --coverage --coverage-path ../coverage/lcov.info .
      working-directory: shelf_modular
      
    - name: Codecov GitHub Action
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  modular_test:
    name: modular_test tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.0'
    
    - name: get packages
      run: flutter pub get
      working-directory: modular_test
    
    - name: Flutter Test
      run: flutter test --coverage --coverage-path ../coverage/lcov.info .
      working-directory: modular_test
      
    - name: Codecov GitHub Action
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
