name: COVERAGE

on: 
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: cd example_package && pub get
#      - name: Run tests
#        run: cd example_package && pub run test
      - name: Code coverage
        id: dart-coverage
        uses: johnpryan/dart-coverage-action@master
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.github_token }}
